Update TypeScript and Angular
I couldn't upgrade to the latest version because I get strange errors
that I can't figure out.

    ERROR: /home/phil/repos/971-Robot-Code/tools/build_rules/js/BUILD:15:11: Transpiling & type-checking TypeScript project @//tools/build_rules/js:ngc.esbuild [tsc -p tsconfig.node.json] failed: (Exit 2): tsc.sh failed: error executing command (from target //tools/build_rules/js:ngc.esbuild) bazel-out/k8-opt-exec-F7C67EFD/bin/external/npm_typescript/tsc.sh --project tsconfig.node.json --outDir tools/build_rules/js --rootDir tools/build_rules/js --declarationDir tools/build_rules/js
    ...
    node_modules/.aspect_rules_js/@angular+compiler-cli@17.2.1_615179293/node_modules/@angular/compiler-cli/private/babel.d.ts(24,17): error TS6137: Cannot import type declaration files. Consider importing 'babel__core' instead of '@types/babel__core'.
    node_modules/.aspect_rules_js/@angular+compiler-cli@17.2.1_615179293/node_modules/@angular/compiler-cli/private/babel.d.ts(27,27): error TS6137: Cannot import type declaration files. Consider importing 'babel__generator' instead of '@types/babel__generator'.
    node_modules/.aspect_rules_js/@types+babel__core@7.20.5/node_modules/@types/babel__core/index.d.ts(1,10): error TS2614: Module '"@babel/generator"' has no exported member 'GeneratorOptions'. Did you mean to use 'import GeneratorOptions from "@babel/generator"' instead?

As an intermediate step, I'm upgrading Angular to version 16. Version
17 gives me that strange error above.

The `in_process_plotter_demo` still seems to work.

    $ bazel run //aos/analysis:in_process_plotter_demo

Signed-off-by: Philipp Schrader <philipp.schrader@gmail.com>
Change-Id: I08349fa98e6db00850705068a51eb188f640e486