Fix bazel query
We currently see this error when running a query:

    $ bazel query //...
    ERROR: /bazel-cache/phil/bazel/_bazel_phil/f1328168c8ac7d35b10d44d44011b547/external/build_bazel_rules_nodejs/internal/node/node.bzl:87:45: invalid escape sequence: \/. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
    ERROR: /bazel-cache/phil/bazel/_bazel_phil/f1328168c8ac7d35b10d44d44011b547/external/build_bazel_rules_nodejs/internal/node/node.bzl:87:64: invalid escape sequence: \.. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
    ERROR: error loading package '': in /bazel-cache/phil/bazel/_bazel_phil/f1328168c8ac7d35b10d44d44011b547/external/build_bazel_rules_nodejs/defs.bzl: Extension 'internal/node/node.bzl' has errors
    Loading: 0 packages loaded

This patch fixes that by disabling this feature on queries for now. At
some point we need to fix this and get rid of the extra flags.

Change-Id: Ia16e3234355159efccba393b92503999678f2a9e